#!/bin/bash

# Update package lists and install required dependencies
apt-get update
apt-get install -y \
  chromium-browser \
  libnss3 \
  libxss1 \
  libasound2 \
  fonts-liberation \
  libappindicator3-1 \
  xdg-utils \
  lsb-release \
  libgbm-dev \
  wget \
  ca-certificates

# Install Playwright and its dependencies (including Chromium)
npx playwright install --with-deps

# Install Node.js dependencies
npm install
